module VerifyExamples.String.Verify.IsInt0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import String.Verify exposing(..)









spec0 : Test.Test
spec0 =
    Test.test "#isInt: \n\n    isInt \"error\" \"42\"\n    --> Ok 42" <|
        \() ->
            Expect.equal
                (
                isInt "error" "42"
                )
                (
                Ok 42
                )