module VerifyExamples.String.Verify.IsInt1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import String.Verify exposing(..)









spec1 : Test.Test
spec1 =
    Test.test "#isInt: \n\n    isInt \"error\" \"a\"\n    --> Err [ \"error\" ]" <|
        \() ->
            Expect.equal
                (
                isInt "error" "a"
                )
                (
                Err [ "error" ]
                )