module VerifyExamples.String.Verify.MaxLength0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import String.Verify exposing(..)









spec0 : Test.Test
spec0 =
    Test.test "#maxLength: \n\n    maxLength 3 \"error\" \"abcd\"\n    --> Err [ \"error\" ]" <|
        \() ->
            Expect.equal
                (
                maxLength 3 "error" "abcd"
                )
                (
                Err [ "error" ]
                )