module VerifyExamples.String.Verify.MaxLength1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import String.Verify exposing(..)









spec1 : Test.Test
spec1 =
    Test.test "#maxLength: \n\n    maxLength 3 \"error\" \"abc\"\n    --> Ok \"abc\"" <|
        \() ->
            Expect.equal
                (
                maxLength 3 "error" "abc"
                )
                (
                Ok "abc"
                )