module VerifyExamples.String.Verify.MinLength1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import String.Verify exposing(..)









spec1 : Test.Test
spec1 =
    Test.test "#minLength: \n\n    minLength 3 \"error\" \"ab\"\n    --> Err [ \"error\" ]" <|
        \() ->
            Expect.equal
                (
                minLength 3 "error" "ab"
                )
                (
                Err [ "error" ]
                )