module VerifyExamples.String.Verify.MinLength0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import String.Verify exposing(..)









spec0 : Test.Test
spec0 =
    Test.test "#minLength: \n\n    minLength 3 \"error\" \"abc\"\n    --> Ok \"abc\"" <|
        \() ->
            Expect.equal
                (
                minLength 3 "error" "abc"
                )
                (
                Ok "abc"
                )