module VerifyExamples.String.Verify.NotBlank0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import String.Verify exposing(..)









spec0 : Test.Test
spec0 =
    Test.test "#notBlank: \n\n    notBlank \"error\" \"\"\n    --> Err [ \"error\" ]" <|
        \() ->
            Expect.equal
                (
                notBlank "error" ""
                )
                (
                Err [ "error" ]
                )