module VerifyExamples.List.Verify.NotEmpty1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import List.Verify exposing(..)









spec1 : Test.Test
spec1 =
    Test.test "#notEmpty: \n\n    notEmpty \"error\" []\n    --> Err [ \"error\" ]" <|
        \() ->
            Expect.equal
                (
                notEmpty "error" []
                )
                (
                Err [ "error" ]
                )