module VerifyExamples.List.Verify.NotEmpty0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import List.Verify exposing(..)









spec0 : Test.Test
spec0 =
    Test.test "#notEmpty: \n\n    notEmpty \"error\" [1]\n    --> Ok [1]" <|
        \() ->
            Expect.equal
                (
                notEmpty "error" [1]
                )
                (
                Ok [1]
                )