module VerifyExamples.Set.Verify.NotEmpty0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import Set.Verify exposing(..)

import Set







spec0 : Test.Test
spec0 =
    Test.test "#notEmpty: \n\n    notEmpty \"error\" <| Set.fromList [ (1, 1) ]\n    --> Ok <| Set.fromList [ (1, 1) ]" <|
        \() ->
            Expect.equal
                (
                notEmpty "error" <| Set.fromList [ (1, 1) ]
                )
                (
                Ok <| Set.fromList [ (1, 1) ]
                )