module VerifyExamples.Maybe.Verify.IsJust0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import Maybe.Verify exposing(..)









spec0 : Test.Test
spec0 =
    Test.test "#isJust: \n\n    isJust \"error\" (Just 42)\n    --> Ok 42 -- It removes the wrapper as well!" <|
        \() ->
            Expect.equal
                (
                isJust "error" (Just 42)
                )
                (
                Ok 42 -- It removes the wrapper as well!
                )