module VerifyExamples.Maybe.Verify.IsJust1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import Maybe.Verify exposing(..)









spec1 : Test.Test
spec1 =
    Test.test "#isJust: \n\n    isJust \"error\" Nothing\n    --> Err [ \"error\" ]" <|
        \() ->
            Expect.equal
                (
                isJust "error" Nothing
                )
                (
                Err [ "error" ]
                )