module VerifyExamples.Verify.AndThen2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import Verify exposing(..)

import String.Verify exposing (notBlank)
import Maybe.Verify exposing (isJust)



validator : Validator String { a | firstName : Maybe String } String
validator =
    validate identity
        |> verify .firstName verifyName
verifyName : Validator String (Maybe String) String
verifyName =
    isJust "You need to provide a first name."
        |> andThen (notBlank "You need to provide a none empty first name.")



spec2 : Test.Test
spec2 =
    Test.test "#andThen: \n\n    validator { firstName = Nothing }\n    --> Err [ \"You need to provide a first name.\" ]" <|
        \() ->
            Expect.equal
                (
                validator { firstName = Nothing }
                )
                (
                Err [ "You need to provide a first name." ]
                )