module VerifyExamples.Verify.Custom2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import Verify exposing(..)

import Maybe.Verify exposing (isJust)



validator : Validator String { a | username : Maybe String, level: Int, strength: Int } (String, Int)
validator =
    validate (,)
        |> verify .username (isJust "You need to provide a username.")
        |> custom (\{level, strength} ->
            if strength > level then
                Err [ "Your strength can exceed your level." ]
            else
                Ok strength
            )



spec2 : Test.Test
spec2 =
    Test.test "#custom: \n\n    validator { username = Just \"Ork1\", level = 3, strength = 5 }\n    --> Err [ \"Your strength can exceed your level.\" ]" <|
        \() ->
            Expect.equal
                (
                validator { username = Just "Ork1", level = 3, strength = 5 }
                )
                (
                Err [ "Your strength can exceed your level." ]
                )