module VerifyExamples.Verify.Custom1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import Verify exposing(..)

import Maybe.Verify exposing (isJust)



validator : Validator String { a | username : Maybe String, level: Int, strength: Int } (String, Int)
validator =
    validate (,)
        |> verify .username (isJust "You need to provide a username.")
        |> custom (\{level, strength} ->
            if strength > level then
                Err [ "Your strength can exceed your level." ]
            else
                Ok strength
            )



spec1 : Test.Test
spec1 =
    Test.test "#custom: \n\n    validator { username = Just \"Ork1\", level = 6, strength = 5 }\n    --> Ok (\"Ork1\", 5)" <|
        \() ->
            Expect.equal
                (
                validator { username = Just "Ork1", level = 6, strength = 5 }
                )
                (
                Ok ("Ork1", 5)
                )