module VerifyExamples.Verify.Custom0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import Verify exposing(..)

import Maybe.Verify exposing (isJust)



validator : Validator String { a | username : Maybe String, level: Int, strength: Int } (String, Int)
validator =
    validate (,)
        |> verify .username (isJust "You need to provide a username.")
        |> custom (\{level, strength} ->
            if strength > level then
                Err [ "Your strength can exceed your level." ]
            else
                Ok strength
            )



spec0 : Test.Test
spec0 =
    Test.test "#custom: \n\n    validator { username = Nothing, level = 3, strength = 5 }\n    --> Err [ \"You need to provide a username.\"\n    -->     , \"Your strength can exceed your level.\"\n    -->     ]" <|
        \() ->
            Expect.equal
                (
                validator { username = Nothing, level = 3, strength = 5 }
                )
                (
                Err [ "You need to provide a username."
                    , "Your strength can exceed your level."
                    ]
                )