module VerifyExamples.Verify.Fail0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import Verify exposing(..)









spec0 : Test.Test
spec0 =
    Test.test "#fail: \n\n    fail \"always fail\" Nothing\n    --> Err [ \"always fail\" ]" <|
        \() ->
            Expect.equal
                (
                fail "always fail" Nothing
                )
                (
                Err [ "always fail" ]
                )