module VerifyExamples.Verify.FromMaybe0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import Verify exposing(..)





hasInitial : String -> Maybe Char
hasInitial str =
    case String.uncons str of
        Just (initial, _) -> Just initial
        Nothing -> Nothing



spec0 : Test.Test
spec0 =
    Test.test "#fromMaybe: \n\n    fromMaybe hasInitial \"error\" \"Christoph\"\n    --> Ok 'C'" <|
        \() ->
            Expect.equal
                (
                fromMaybe hasInitial "error" "Christoph"
                )
                (
                Ok 'C'
                )