module VerifyExamples.Verify.FromMaybe1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import Verify exposing(..)





hasInitial : String -> Maybe Char
hasInitial str =
    case String.uncons str of
        Just (initial, _) -> Just initial
        Nothing -> Nothing



spec1 : Test.Test
spec1 =
    Test.test "#fromMaybe: \n\n    fromMaybe hasInitial \"error\" \"\"\n    --> Err [ \"error\" ]" <|
        \() ->
            Expect.equal
                (
                fromMaybe hasInitial "error" ""
                )
                (
                Err [ "error" ]
                )