module VerifyExamples.Verify.Keep0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import Verify exposing(..)

import Maybe.Verify exposing (isJust)



validator : Validator String { a | id : Int, firstName : Maybe String } (Int, String)
validator =
    validate (,)
        |> keep .id
        |> verify .firstName (isJust "You need to provide a first name.")



spec0 : Test.Test
spec0 =
    Test.test "#keep: \n\n    validator { id = 1, firstName = Just \"Stöffel\" }\n    --> Ok (1, \"Stöffel\")" <|
        \() ->
            Expect.equal
                (
                validator { id = 1, firstName = Just "Stöffel" }
                )
                (
                Ok (1, "Stöffel")
                )