module VerifyExamples.Verify.Ok0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import Verify exposing(..)









spec0 : Test.Test
spec0 =
    Test.test "#ok: \n\n    ok \"always ok\" Nothing\n    --> Ok \"always ok\"" <|
        \() ->
            Expect.equal
                (
                ok "always ok" Nothing
                )
                (
                Ok "always ok"
                )