module VerifyExamples.Verify.Validate0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import Verify exposing(..)



type alias User =
    { id : Int
    , name : String
    }

validator : Validator String { a | id : Int, firstName : Maybe String } User
validator =
    validate User
        |> keep .id
        |> verify .firstName (isJust "You need to provide a first name.")



spec0 : Test.Test
spec0 =
    Test.test "#validate: \n\n    validator { id = 1, firstName = Just \"Stöffel\" }\n    --> Ok { id = 1, firstName = \"Stöffel\" }" <|
        \() ->
            Expect.equal
                (
                validator { id = 1, firstName = Just "Stöffel" }
                )
                (
                Ok { id = 1, firstName = "Stöffel" }
                )