module VerifyExamples.Verify.Validate1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import Verify exposing(..)



type alias User =
    { id : Int
    , name : String
    }

validator : Validator String { a | id : Int, firstName : Maybe String } User
validator =
    validate User
        |> keep .id
        |> verify .firstName (isJust "You need to provide a first name.")



spec1 : Test.Test
spec1 =
    Test.test "#validate: \n\n    validator { firstName = Nothing }\n    --> Err [ \"You need to provide a first name.\" ]" <|
        \() ->
            Expect.equal
                (
                validator { firstName = Nothing }
                )
                (
                Err [ "You need to provide a first name." ]
                )