module VerifyExamples.Dict.Verify.NotEmpty1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import Dict.Verify exposing(..)

import Dict







spec1 : Test.Test
spec1 =
    Test.test "#notEmpty: \n\n    notEmpty \"error\" <| Dict.empty\n    --> Err [ \"error\" ]" <|
        \() ->
            Expect.equal
                (
                notEmpty "error" <| Dict.empty
                )
                (
                Err [ "error" ]
                )