module VerifyExamples.Dict.Verify.NotEmpty0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import Dict.Verify exposing(..)

import Dict







spec0 : Test.Test
spec0 =
    Test.test "#notEmpty: \n\n    notEmpty \"error\" <| Dict.fromList [ (1, 1) ]\n    --> Ok <| Dict.fromList [ (1, 1) ]" <|
        \() ->
            Expect.equal
                (
                notEmpty "error" <| Dict.fromList [ (1, 1) ]
                )
                (
                Ok <| Dict.fromList [ (1, 1) ]
                )